//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Extends.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Company.Extends.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string website_about_us {
            get {
                return ResourceManager.GetString("website_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office at Hanoi.
        /// </summary>
        public static string website_address_1 {
            get {
                return ResourceManager.GetString("website_address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office at HCM city.
        /// </summary>
        public static string website_address_2 {
            get {
                return ResourceManager.GetString("website_address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanoi.
        /// </summary>
        public static string website_address1_short {
            get {
                return ResourceManager.GetString("website_address1_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.HCM.
        /// </summary>
        public static string website_address2_short {
            get {
                return ResourceManager.GetString("website_address2_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string website_articale_category_id {
            get {
                return ResourceManager.GetString("website_articale_category_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariticle content.
        /// </summary>
        public static string website_articale_language_content {
            get {
                return ResourceManager.GetString("website_articale_language_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariticle describle.
        /// </summary>
        public static string website_articale_language_describle {
            get {
                return ResourceManager.GetString("website_articale_language_describle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariticle image.
        /// </summary>
        public static string website_articale_language_image {
            get {
                return ResourceManager.GetString("website_articale_language_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article name.
        /// </summary>
        public static string website_articale_language_name {
            get {
                return ResourceManager.GetString("website_articale_language_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string website_blog_by {
            get {
                return ResourceManager.GetString("website_blog_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string website_blog_categories {
            get {
                return ResourceManager.GetString("website_blog_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string website_blog_get_connected {
            get {
                return ResourceManager.GetString("website_blog_get_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Posts.
        /// </summary>
        public static string website_blog_recent_posts {
            get {
                return ResourceManager.GetString("website_blog_recent_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string website_button_close {
            get {
                return ResourceManager.GetString("website_button_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string website_button_send_message {
            get {
                return ResourceManager.GetString("website_button_send_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string website_button_view_more {
            get {
                return ResourceManager.GetString("website_button_view_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string website_contact_us {
            get {
                return ResourceManager.GetString("website_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright byThang Hoa.
        /// </summary>
        public static string website_copyright {
            get {
                return ResourceManager.GetString("website_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time.
        /// </summary>
        public static string website_create_time {
            get {
                return ResourceManager.GetString("website_create_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string website_create_user {
            get {
                return ResourceManager.GetString("website_create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string website_enable {
            get {
                return ResourceManager.GetString("website_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string website_fullname {
            get {
                return ResourceManager.GetString("website_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string website_get_in_touch {
            get {
                return ResourceManager.GetString("website_get_in_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string website_language_select_title_en {
            get {
                return ResourceManager.GetString("website_language_select_title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string website_language_select_title_vi {
            get {
                return ResourceManager.GetString("website_language_select_title_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag-icon flag-icon-us.
        /// </summary>
        public static string website_language_selected_icon_name {
            get {
                return ResourceManager.GetString("website_language_selected_icon_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string website_language_selected_title {
            get {
                return ResourceManager.GetString("website_language_selected_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string website_language_selected_title_admin {
            get {
                return ResourceManager.GetString("website_language_selected_title_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edit time.
        /// </summary>
        public static string website_last_edit_time {
            get {
                return ResourceManager.GetString("website_last_edit_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edit user.
        /// </summary>
        public static string website_last_edit_user {
            get {
                return ResourceManager.GetString("website_last_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string website_link {
            get {
                return ResourceManager.GetString("website_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string website_link_blog {
            get {
                return ResourceManager.GetString("website_link_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string website_link_home {
            get {
                return ResourceManager.GetString("website_link_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live chat.
        /// </summary>
        public static string website_live_chat_link {
            get {
                return ResourceManager.GetString("website_live_chat_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang Hoa.
        /// </summary>
        public static string website_logo_title {
            get {
                return ResourceManager.GetString("website_logo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string website_message {
            get {
                return ResourceManager.GetString("website_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string website_null {
            get {
                return ResourceManager.GetString("website_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oder.
        /// </summary>
        public static string website_order {
            get {
                return ResourceManager.GetString("website_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Clients.
        /// </summary>
        public static string website_our_client {
            get {
                return ResourceManager.GetString("website_our_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Solutions.
        /// </summary>
        public static string website_our_products {
            get {
                return ResourceManager.GetString("website_our_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string website_placeholder_email {
            get {
                return ResourceManager.GetString("website_placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string website_privacy_policy {
            get {
                return ResourceManager.GetString("website_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string website_slider_email {
            get {
                return ResourceManager.GetString("website_slider_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string website_slider_signup {
            get {
                return ResourceManager.GetString("website_slider_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact.
        /// </summary>
        public static string website_solution_contact {
            get {
                return ResourceManager.GetString("website_solution_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of services.
        /// </summary>
        public static string website_terms_of_services {
            get {
                return ResourceManager.GetString("website_terms_of_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang Hoa.
        /// </summary>
        public static string website_title {
            get {
                return ResourceManager.GetString("website_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string website_video_tour {
            get {
                return ResourceManager.GetString("website_video_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch video.
        /// </summary>
        public static string website_video_watch {
            get {
                return ResourceManager.GetString("website_video_watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string website_visible {
            get {
                return ResourceManager.GetString("website_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why us.
        /// </summary>
        public static string website_why_us {
            get {
                return ResourceManager.GetString("website_why_us", resourceCulture);
            }
        }
    }
}
